---
title: "Data wrangling"
description: |
  How to work efficiently with data in R 
author:
  - name: Danielle Navarro 
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The final section comes in two parts. It discusses reading data from and writing data to a CSV file, and introduces the pipe. Much of this section is devoted to a discussion of calculating descriptive statistics in R. The resources:

- ["Hello data" slides](https://slides.djnavarro.net/starting-readr)
- [RStudio Cloud project 978818](https://rstudio.cloud/project/978818)
- [YouTube playlist 45 min](https://www.youtube.com/watch?v=lpbqlu_Sk3M&list=PLRPB0ZzEYegPYKRLwJRh4AbWWSiIlzmC7)
- [The reasoning experiment](https://robust-tools.djnavarro.net/reasoning/)

The second part provides an introduction to data wrangling in R, mostly focusing on dplyr. Topics covered include: extracting a subset of the data, rearranging the data, computing new variables in a data set, merging multiple data sets, and pivoting data between "long" and "wide" forms. Resources:

- [Data wrangling slides](https://slides.djnavarro.net/starting-dplyr)
- [RStudio Cloud project 1006868](https://rstudio.cloud/project/1006868)
- [YouTube playlist 140 min](https://www.youtube.com/watch?v=_LiB4nUKi3o&list=PLRPB0ZzEYegNFsivhQWTFvKvpEc504EPH)

Good luck! And as always, please get in touch with me on slack if you have any questions!

