---
title: "Week 3"
description: |
 reproducibility project planning
author:
  - name: Jenny Richmond
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Your task

Choose a paper from the option list below and work as a team to reproduce the descriptive statistics and plots. For each of the papers we have checked that the task is possible and that the data are interesting. The task is NOT EASY though. You will probably not learn all the functions you need from Danielle so get comfortable with googling and asking for help when you need it. 

If you want to look at an example of what is possible re open data/code, check out this [paper by Wahlheim](https://journals.sagepub.com/doi/full/10.1177/0956797620952797), [OSF](https://osf.io/89zmj/). It is an A+ example of how to make it easy for other people to work with your data, so is a good exemplar to look at when you are thinking about what your authors could have done differently. 

Have a look at the options below, decide which one you are interested in working on and add your name and RPubs details to [this spreadsheet](https://docs.google.com/spreadsheets/d/15bQvQGFmaHqUlmGXzpkIc-wvhkqZu5pjhXTLKRsG43s/edit?usp=sharing). Read the paper carefully and write a [summary and reaction](https://docs.google.com/document/d/1XLi1DrYP9QdGKYYJ3j0Mr905puc8ml_YycB2RXdtlD4/edit?usp=sharing). Bring your S&R to workshop to share with your group so you can make a quick start on project planning. 

## Option 1

Carstensen, L. L., Shavit, Y. Z., & Barnes, J. T. (2020). Age Advantages in Emotional Experience Persist Even Under Threat From the COVID-19 Pandemic. *Psychological Science, 31(11)*, 1374–1385. https://doi.org/10.1177/0956797620967261

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797620967261#articleCitationDownloadContainer)
- [OSF](https://osf.io/h7uqv/)


## Option 2

Pfattheicher, S., Nockur, L., Böhm, R., Sassenrath, C., & Petersen, M. B. (2020). The Emotional Path to Action: Empathy Promotes Physical Distancing and Wearing of Face Masks During the COVID-19 Pandemic. *Psychological Science, 31(11)*, 1363–1373. https://doi.org/10.1177/0956797620964422

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797620964422)
- [OSF](https://osf.io/pq3ky/)

## Option 3

Tybur, J. M., Lieberman, D., Fan, L., Kupfer, T. R., & de Vries, R. E. (2020). Behavioral Immune Trade-Offs: Interpersonal Value Relaxes Social Pathogen Avoidance. *Psychological Science, 31(10)*, 1211–1221. https://doi.org/10.1177/0956797620960011

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797620960011)
- [OSF](https://osf.io/4agk8/)

## Option 4

Smith LE, Mottershaw AL, Egan M, Waller J, Marteau TM, Rubin GJ (2020) The impact of believing you have had COVID-19 on self-reported behaviour: Cross-sectional survey. *PLoS ONE 15(11)*: e0240399.

- [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0240399)
- [OSF](https://osf.io/y7eha/)


## Option 5

Folk, D., Okabe-Miyamoto, K., Dunn, E., Lyubomirsky, S., & Donnellan, B. (2020). Did social connection decline during the first wave of COVID-19?: the role of extraversion. *Collabra: Psychology, 6(1)*.

- [paper](https://online.ucpress.edu/collabra/article/6/1/37/11446)
- [OSF](https://osf.io/zj9fv/?view_only=b6f77e38fbb54f839d6c2bd1fb8d41c2)



