---
title: "Week 9"
description: |
 workflow for reproducible research
author:
  - name: Jenny Richmond
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In Week 9 workshops we are going to talk about workflows for reproducibility. I had a super hard time narrowing down the list of resources I wanted you to be exposed to so we are going to work in smaller groups. 

Choose which of the following talks you want to watch/papers you want to read. and add your name to [this spreadsheet](https://docs.google.com/spreadsheets/d/15bQvQGFmaHqUlmGXzpkIc-wvhkqZu5pjhXTLKRsG43s/edit?usp=sharing).

### Option 1 Danielle Navarro [Save your sanity workflow](https://thebox.unsw.edu.au/92F645F0-1184-11EA-918EDA956A25D116)

### Option 2 Sharla Gelfand [Don't repeat yourself talk to yourself](https://www.rstudio.com/resources/rstudioconf-2020/don-t-repeat-yourself-talk-to-yourself-repeated-reporting-in-the-r-universe/)


### Option 3 Julia Stewart Lowndes [R for better science in less time](https://www.youtube.com/watch?v=Z8PqwFPqn6Y)

### Option 4 Erin Buchanan [using papaja to write reproducible report](https://youtu.be/I_HW5Rraqg8)

### Option 5 Greg Wilson [Good enough practices in scientific computering](https://drive.google.com/open?id=1UYeGaalYXIA2fuMN_q_BIoP0mqypoO56)

### Option 6 Jenny Bryan [Excuse me to you have a moment to talk about version control](https://drive.google.com/file/d/1FENix84Mc6QjhNsR5ukNDY5Q3GY66GKE/view?usp=sharing)

### Option 7 Karl Broman & Kara woo [Data organization in spreadsheets](https://drive.google.com/open?id=1wSlp4IVsmCvs20OtJuZIR-8NL_BP6oIE)
