---
title: "Week 3"
description: |
 reproducibility project planning
author:
  - name: Jenny Richmond
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Your task

Choose a paper from the option list below and work as a team to reproduce the descriptive statistics and plots. For each of the papers we have checked that the task is possible and that the data are interesting. The task is NOT EASY though. You will probably not learn all the functions you need from Danielle so get comfortable with googling and asking for help when you need it. 

If you want to look at an example of what is possible re open data/code, check out this [paper by Wahlheim](https://journals.sagepub.com/doi/full/10.1177/0956797620952797), [OSF](https://osf.io/89zmj/). It is an A+ example of how to make it easy for other people to work with your data, so is a good exemplar to look at when you are thinking about what your authors could have done differently. 

Have a look at the options below, decide which one you are interested in working on and add your name and RPubs details to [this spreadsheet](https://docs.google.com/spreadsheets/d/15bQvQGFmaHqUlmGXzpkIc-wvhkqZu5pjhXTLKRsG43s/edit?usp=sharing). Read the paper carefully and write a [summary and reaction](https://docs.google.com/document/d/1XLi1DrYP9QdGKYYJ3j0Mr905puc8ml_YycB2RXdtlD4/edit?usp=sharing). Bring your S&R to workshop to share with your group so you can make a quick start on project planning. 

## Option 1

Haigh, M., & Birch, H. A. (2021). When ‘Scientists Say’ Coffee Is Good for You One Day and Bad for You the Next: Do Generic Attributions to ‘Scientists’ and ‘Experts’ Amplify Perceived Conflict? *Collabra: Psychology, 7(1)*.

- [paper](https://online.ucpress.edu/collabra/article/7/1/23447/116975/When-Scientists-Say-Coffee-Is-Good-for-You-One-Day)


## Option 2

Harris, E. A., & Van Bavel, J. J. (2021). Preregistered Replication of “Feeling superior is a bipartisan issue: Extremity (not direction) of political views predicts perceived belief superiority”. *Psychological Science, 32(3)*, 451-458.

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797620968792)


## Option 3

Humiston GB, Wamsley EJ (2019) Unlearning implicit social biases during sleep: A failure to replicate. *PLoS ONE 14(1): e0211416*.

- [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0211416)


## Option 4

Nichols AD, Lang M, Kavanagh C, Kundt R, Yamada J, Ariely D, et al. (2020) Replicating and extending the effects of auditory religious cues on dishonest behavior. *PLoS ONE 15(8): e0237007*.

- [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0237007)


## Option 5

Walter, K. V., Conroy-Beam, D., Buss, D. M., Asao, K., Sorokowska, A., Sorokowski, P., ... & Zupančič, M. (2020). Sex differences in mate preferences across 45 countries: A large-scale replication. *Psychological science, 31(4)*, 408-423.

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797620904154)




